In [1]:
import pandas as pd
import torch
from torch import nn
from settings import config

In [2]:
class Network(nn.Module):
    def __init__(self, in_dim, hidden_1, hidden_2, hidden_3, hidden_4):
        super().__init__()
        self.layers = nn.Sequential(
            nn.Linear(in_dim, hidden_1),
            nn.BatchNorm1d(hidden_1),
            nn.ReLU(),
            nn.Linear(hidden_1, hidden_2),
            nn.BatchNorm1d(hidden_2),
            nn.ReLU(),
            nn.Linear(hidden_2, hidden_3),
            nn.BatchNorm1d(hidden_3),
            nn.ReLU(),
            nn.Linear(hidden_3, hidden_4),
            nn.BatchNorm1d(hidden_4),
            nn.ReLU(),
            nn.Linear(hidden_4, 1)
        )

    def forward(self, x):
        y = self.layers(x)
        return y

In [3]:
model = torch.load('model.pth', map_location=config['device'])

C:\Users\Lufiende\AppData\Local\Temp\ipykernel_17496\2000844005.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model = torch.load('model.pth', map_location=config['device'])

In [4]:
data = pd.read_csv('./one_hot_testB.csv')
data

,Unnamed: 0,SaleID,regDate,power,kilometer,offerType,creatDate,price,v_0,v_1,...,fuelType_6.0,fuelType_-1,gearbox_0.0,gearbox_1.0,gearbox_-1,seller_0,seller_1,notRepairedDamage_-1.0,notRepairedDamage_0.0,notRepairedDamage_1.0
0,0,200000,0.375190,0.168333,1.000000,0,0.995074,NaN,0.534961,0.103380,...,False,False,True,False,False,True,False,False,True,False
1,1,200001,0.166701,0.121667,0.379310,0,0.995173,NaN,0.615730,0.090478,...,False,False,True,False,False,True,False,False,True,False
2,2,200002,0.748743,0.200000,0.310345,0,0.995124,NaN,0.683578,0.660127,...,False,False,True,False,False,True,False,True,False,False
3,3,200003,0.458520,0.096667,1.000000,0,0.995372,NaN,0.564556,0.717176,...,False,False,True,False,False,True,False,False,True,False
4,4,200004,0.498733,0.193333,1.000000,0,0.994974,NaN,0.604918,0.099881,...,False,True,True,False,False,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49995,249995,0.543110,0.250000,1.000000,0,0.995124,NaN,0.726199,0.085330,...,False,True,False,True,False,True,False,True,False,False
49996,49996,249996,0.913756,0.298333,0.241379,0,0.995820,NaN,0.806993,0.084104,...,False,False,True,False,False,True,False,False,True,False
49997,49997,249997,0.543964,0.245000,0.827586,0,0.995472,NaN,0.718157,0.085256,...,False,False,False,True,False,True,False,False,True,False
49998,49998,249998,0.458938,0.293333,1.000000,0,0.996019,NaN,0.688952,0.094576,...,False,False,False,True,False,True,False,False,True,False
49999,49999,249999,0.749166,0.000000,0.172414,0,0.999701,NaN,0.633231,0.729779,...,False,False,True,False,False,True,False,False,True,False

In [5]:
data.shape

(50000, 337)

In [6]:
data.columns

Index(['Unnamed: 0', 'SaleID', 'regDate', 'power', 'kilometer', 'offerType',
       'creatDate', 'price', 'v_0', 'v_1',
       ...
       'fuelType_6.0', 'fuelType_-1', 'gearbox_0.0', 'gearbox_1.0',
       'gearbox_-1', 'seller_0', 'seller_1', 'notRepairedDamage_-1.0',
       'notRepairedDamage_0.0', 'notRepairedDamage_1.0'],
      dtype='object', length=337)

In [7]:
data = data.drop(columns=['Unnamed: 0', 'price'])
test = data.drop(columns='SaleID')

In [8]:
test.shape
test

,regDate,power,kilometer,offerType,creatDate,v_0,v_1,v_2,v_3,v_4,...,fuelType_6.0,fuelType_-1,gearbox_0.0,gearbox_1.0,gearbox_-1,seller_0,seller_1,notRepairedDamage_-1.0,notRepairedDamage_0.0,notRepairedDamage_1.0
0,0.375190,0.168333,1.000000,0,0.995074,0.534961,0.103380,0.159506,0.510304,0.480119,...,False,False,True,False,False,True,False,False,True,False
1,0.166701,0.121667,0.379310,0,0.995173,0.615730,0.090478,0.157586,0.499234,0.294734,...,False,False,True,False,False,True,False,False,True,False
2,0.748743,0.200000,0.310345,0,0.995124,0.683578,0.660127,0.149114,0.281833,0.445674,...,False,False,True,False,False,True,False,True,False,False
3,0.458520,0.096667,1.000000,0,0.995372,0.564556,0.717176,0.180943,0.524459,0.489885,...,False,False,True,False,False,True,False,False,True,False
4,0.498733,0.193333,1.000000,0,0.994974,0.604918,0.099881,0.141944,0.452158,0.401879,...,False,True,True,False,False,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,0.543110,0.250000,1.000000,0,0.995124,0.726199,0.085330,0.193312,0.388370,0.320372,...,False,True,False,True,False,True,False,True,False,False
49996,0.913756,0.298333,0.241379,0,0.995820,0.806993,0.084104,0.231282,0.268707,0.421837,...,False,False,True,False,False,True,False,False,True,False
49997,0.543964,0.245000,0.827586,0,0.995472,0.718157,0.085256,0.189541,0.407870,0.328522,...,False,False,False,True,False,True,False,False,True,False
49998,0.458938,0.293333,1.000000,0,0.996019,0.688952,0.094576,0.141640,0.399312,0.225080,...,False,False,False,True,False,True,False,False,True,False
49999,0.749166,0.000000,0.172414,0,0.999701,0.633231,0.729779,0.213465,0.379410,0.549778,...,False,False,True,False,False,True,False,False,True,False

In [9]:
for u in test.columns:
    if test[u].dtype==bool:
        test[u]=test[u].astype('int')

test = torch.tensor(test.values, dtype=torch.float32)

In [10]:
pred = model(test)

In [11]:
pred

tensor([[1142.9498],
        [1890.7131],
        [8528.2988],
        ...,
        [5325.9292],
        [4598.1157],
        [5691.9331]], grad_fn=<AddmmBackward0>)

In [12]:
price = pd.DataFrame(pred.detach().cpu().numpy(), columns=['price'])

In [13]:
res = pd.concat([data.SaleID, price], axis=1)

In [14]:
res

       SaleID         price
0      200000   1142.949829
1      200001   1890.713135
2      200002   8528.298828
3      200003   1495.278442
4      200004   1911.961304
...       ...           ...
49995  249995   6622.774902
49996  249996  17543.621094
49997  249997   5325.929199
49998  249998   4598.115723
49999  249999   5691.933105

[50000 rows x 2 columns]

In [15]:
res.to_csv('output.csv')