## 写在最前面

这门课程得主要目的是通过真实的数据，以实战的方式了解数据分析的流程和熟悉数据分析python的基本操作。知道了课程的目的之后，我们接下来我们要正式的开始数据分析的实战教学，完成kaggle上[泰坦尼克的任务](https://www.kaggle.com/c/titanic/overview)，实战数据分析全流程。
这里有两份资料需要大家准备：
图书《Python for Data Analysis》第六章和 baidu.com &
bing.com（善用搜索引擎）

## 1 第一章：数据加载

### 1.1 载入数据
数据集下载 https://www.kaggle.com/c/titanic/overview

#### 1.1.1 任务一：导入numpy和pandas

In [43]:
import numpy as np
import pandas as pd

【提示】如果加载失败，学会如何在你的python环境下安装numpy和pandas这两个库

#### 1.1.2 任务二：载入数据
(1) 使用相对路径载入数据  
(2) 使用绝对路径载入数据

In [44]:
relPath_loadData = pd.read_csv('Day2 - train.csv')
print(relPath_loadData)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [45]:
import os 

absPath = os.getcwd()
print(absPath)

absPath = absPath + r'\Day2 - train.csv'
absPath_loadData = pd.read_csv(absPath)

print(absPath_loadData)

f:\Programming\Jupyter\Workspace\2024.8 - AI-Training-Camp-Practice
     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

【提示】相对路径载入报错时，尝试使用os.getcwd()查看当前工作目录。  
【思考】知道数据加载的方法后，试试pd.read_csv()和pd.read_table()的不同，了解一下'.tsv'和'.csv'的不同，如何加载这两个数据集？

In [46]:
dfCsvData = relPath_loadData
dfTableData = pd.read_table('Day2 - train.csv')

# 尝试不同函数读取csv文件并输出
strCsvData = dfCsvData.to_string()
print(strCsvData)

print('\n' * 5 )

strTableData = dfTableData.to_string()
print(strTableData)

# 尝试替换逗号为制表符并输出
strOrigCsv = ''

with open('Day2 - train.csv' , 'r') as f:
    strOrigCsv = f.read()
    f.close()

strOrigCsv = strOrigCsv.replace(',','\t')

with open('Day2 - train.tsv' , 'w') as f:
    f.write(strOrigCsv)
    f.close()

dfTableData = pd.read_table('Day2 - train.tsv')
print(dfTableData.to_string())

# TSV与CSV的区别：
# 1. TSV是用制表符（Tab,'\t'）作为字段值的分隔符；CSV是用半角逗号（','）作为字段值的分隔符； 
# 2. IANA规定的标准TSV格式，字段值之中是不允许出现制表符的。

# read_csv() : 从文件、url、文件型对象中加载带分隔符的数据，默认分隔符为逗号，
# 如果文件是用逗号分隔的，则read_csv更合适，比如给的这个

# read_table() : 从文件、url、文件型对象中加载带分隔符的数据，默认分隔符为制表符，
# 如果文件是用制表符分隔的，则read_table更合适

     PassengerId  Survived  Pclass                                                                                Name     Sex    Age  SibSp  Parch              Ticket      Fare            Cabin Embarked
0              1         0       3                                                             Braund, Mr. Owen Harris    male  22.00      1      0           A/5 21171    7.2500              NaN        S
1              2         1       1                                 Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.00      1      0            PC 17599   71.2833              C85        C
2              3         1       3                                                              Heikkinen, Miss. Laina  female  26.00      0      0    STON/O2. 3101282    7.9250              NaN        S
3              4         1       1                                        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.00      1      0              113803   53.1000             C123        S
4              5         0       3                                                            Allen, Mr. William Henry    male  35.00      0      0              373450    8.0500              NaN        S
5              6         0       3                                                                    Moran, Mr. James    male    NaN      0      0              330877    8.4583              NaN        Q
6              7         0       1                                                             McCarthy, Mr. Timothy J    male  54.00      0      0               17463   51.8625              E46        S
7              8         0       3                                                      Palsson, Master. Gosta Leonard    male   2.00      3      1              349909   21.0750              NaN        S
8              9         1       3                                   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.00      0      2              347742   11.1333              NaN        S
9             10         1       2                                                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.00      1      0              237736   30.0708              NaN        C
10            11         1       3                                                     Sandstrom, Miss. Marguerite Rut  female   4.00      1      1             PP 9549   16.7000               G6        S
11            12         1       1                                                            Bonnell, Miss. Elizabeth  female  58.00      0      0              113783   26.5500             C103        S
12            13         0       3                                                      Saundercock, Mr. William Henry    male  20.00      0      0           A/5. 2151    8.0500              NaN        S
13            14         0       3                                                         Andersson, Mr. Anders Johan    male  39.00      1      5              347082   31.2750              NaN        S
14            15         0       3                                                Vestrom, Miss. Hulda Amanda Adolfina  female  14.00      0      0              350406    7.8542              NaN        S
15            16         1       2                                                    Hewlett, Mrs. (Mary D Kingcome)   female  55.00      0      0              248706   16.0000              NaN        S
16            17         0       3                                                                Rice, Master. Eugene    male   2.00      4      1              382652   29.1250              NaN        Q
17            18         1       2                                                        Williams, Mr. Charles Eugene    male    NaN      0      0              244373   13.0000              NaN        S
18            19         0       3                             Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)  female  31.00      1      0              345763   18.0000              NaN        S
19            20         1       3                                                             Masselmani, Mrs. Fatima  female    NaN      0      0                2649    7.2250              NaN        C
20            21         0       2                                                                Fynney, Mr. Joseph J    male  35.00      0      0              239865   26.0000              NaN        S
21            22         1       2                                                               Beesley, Mr. Lawrence    male  34.00      0      0              248698   13.0000              D56        S
22            23         1       3                                                         McGowan, Miss. Anna "Annie"  female  15.00      0      0              330923    8.0292              NaN        Q
23            24         1       1                                                        Sloper, Mr. William Thompson    male  28.00      0      0              113788   35.5000               A6        S
24            25         0       3                                                       Palsson, Miss. Torborg Danira  female   8.00      3      1              349909   21.0750              NaN        S
25            26         1       3                           Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)  female  38.00      1      5              347077   31.3875              NaN        S
26            27         0       3                                                             Emir, Mr. Farred Chehab    male    NaN      0      0                2631    7.2250              NaN        C
27            28         0       1                                                      Fortune, Mr. Charles Alexander    male  19.00      3      2               19950  263.0000      C23 C25 C27        S
28            29         1       3                                                       O'Dwyer, Miss. Ellen "Nellie"  female    NaN      0      0              330959    7.8792              NaN        Q
29            30         0       3                                                                 Todoroff, Mr. Lalio    male    NaN      0      0              349216    7.8958              NaN        S
30            31         0       1                                                            Uruchurtu, Don. Manuel E    male  40.00      0      0            PC 17601   27.7208              NaN        C
31            32         1       1                                      Spencer, Mrs. William Augustus (Marie Eugenie)  female    NaN      1      0            PC 17569  146.5208              B78        C
32            33         1       3                                                            Glynn, Miss. Mary Agatha  female    NaN      0      0              335677    7.7500              NaN        Q
33            34         0       2                                                               Wheadon, Mr. Edward H    male  66.00      0      0          C.A. 24579   10.5000              NaN        S
34            35         0       1                                                             Meyer, Mr. Edgar Joseph    male  28.00      1      0            PC 17604   82.1708              NaN        C
35            36         0       1                                                      Holverson, Mr. Alexander Oskar    male  42.00      1      0              113789   52.0000              NaN        S
36            37         1       3                                                                    Mamee, Mr. Hanna    male    NaN      0      0                2677    7.2292              NaN        C
37            38         0       3                                                            Cann, Mr. Ernest Charles    male  21.00      0      0          A./5. 2152    8.0500              NaN        S
38            39         0       3                                                  Vander Planke, Miss. Augusta Maria  female  18.00      2      0              345764   18.0000              NaN        S
39            40         1       3                                                         Nicola-Yarred, Miss. Jamila  female  14.00      1      0                2651   11.2417              NaN        C
40            41         0       3                                      Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female  40.00      1      0                7546    9.4750              NaN        S
41            42         0       2                            Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)  female  27.00      1      0               11668   21.0000              NaN        S
42            43         0       3                                                                 Kraeff, Mr. Theodor    male    NaN      0      0              349253    7.8958              NaN        C
43            44         1       2                                            Laroche, Miss. Simonne Marie Anne Andree  female   3.00      1      2       SC/Paris 2123   41.5792              NaN        C
44            45         1       3                                                       Devaney, Miss. Margaret Delia  female  19.00      0      0              330958    7.8792              NaN        Q
45            46         0       3                                                            Rogers, Mr. William John    male    NaN      0      0     S.C./A.4. 23567    8.0500              NaN        S
46            47         0       3                                                                   Lennon, Mr. Denis    male    NaN      1      0              370371   15.5000              NaN        Q
47            48         1       3                                                           O'Driscoll, Miss. Bridget  female    NaN      0      0               14311    7.7500              NaN        Q
48            49         0       3                                                                 Samaan, Mr. Youssef    male    NaN      2      0                2662   21.6792              NaN        C
49            50         0       3                                       Arnold-Franchi, Mrs. Josef (Josefine Franchi)  female  18.00      1      0              349237   17.8000              NaN        S
50            51         0       3                                                          Panula, Master. Juha Niilo    male   7.00      4      1             3101295   39.6875              NaN        S
51            52         0       3                                                        Nosworthy, Mr. Richard Cater    male  21.00      0      0          A/4. 39886    7.8000              NaN        S
52            53         1       1                                            Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  49.00      1      0            PC 17572   76.7292              D33        C
53            54         1       2                                  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)  female  29.00      1      0                2926   26.0000              NaN        S
54            55         0       1                                                      Ostby, Mr. Engelhart Cornelius    male  65.00      0      1              113509   61.9792              B30        C
55            56         1       1                                                                   Woolner, Mr. Hugh    male    NaN      0      0               19947   35.5000              C52        S
56            57         1       2                                                                   Rugg, Miss. Emily  female  21.00      0      0          C.A. 31026   10.5000              NaN        S
57            58         0       3                                                                 Novel, Mr. Mansouer    male  28.50      0      0                2697    7.2292              NaN        C
58            59         1       2                                                        West, Miss. Constance Mirium  female   5.00      1      2          C.A. 34651   27.7500              NaN        S
59            60         0       3                                                  Goodwin, Master. William Frederick    male  11.00      5      2             CA 2144   46.9000              NaN        S
60            61         0       3                                                               Sirayanian, Mr. Orsen    male  22.00      0      0                2669    7.2292              NaN        C
61            62         1       1                                                                 Icard, Miss. Amelie  female  38.00      0      0              113572   80.0000              B28      NaN
62            63         0       1                                                         Harris, Mr. Henry Birkhardt    male  45.00      1      0               36973   83.4750              C83        S
63            64         0       3                                                               Skoog, Master. Harald    male   4.00      3      2              347088   27.9000              NaN        S
64            65         0       1                                                               Stewart, Mr. Albert A    male    NaN      0      0            PC 17605   27.7208              NaN        C
65            66         1       3                                                            Moubarek, Master. Gerios    male    NaN      1      1                2661   15.2458              NaN        C
66            67         1       2                                                        Nye, Mrs. (Elizabeth Ramell)  female  29.00      0      0          C.A. 29395   10.5000              F33        S
67            68         0       3                                                            Crease, Mr. Ernest James    male  19.00      0      0           S.P. 3464    8.1583              NaN        S
68            69         1       3                                                     Andersson, Miss. Erna Alexandra  female  17.00      4      2             3101281    7.9250              NaN        S
69            70         0       3                                                                   Kink, Mr. Vincenz    male  26.00      2      0              315151    8.6625              NaN        S
70            71         0       2                                                          Jenkin, Mr. Stephen Curnow    male  32.00      0      0          C.A. 33111   10.5000              NaN        S
71            72         0       3                                                          Goodwin, Miss. Lillian Amy  female  16.00      5      2             CA 2144   46.9000              NaN        S
72            73         0       2                                                                Hood, Mr. Ambrose Jr    male  21.00      0      0        S.O.C. 14879   73.5000              NaN        S
73            74         0       3                                                         Chronopoulos, Mr. Apostolos    male  26.00      1      0                2680   14.4542              NaN        C
74            75         1       3                                                                       Bing, Mr. Lee    male  32.00      0      0                1601   56.4958              NaN        S
75            76         0       3                                                             Moen, Mr. Sigurd Hansen    male  25.00      0      0              348123    7.6500            F G73        S
76            77         0       3                                                                   Staneff, Mr. Ivan    male    NaN      0      0              349208    7.8958              NaN        S
77            78         0       3                                                            Moutal, Mr. Rahamin Haim    male    NaN      0      0              374746    8.0500              NaN        S
78            79         1       2                                                       Caldwell, Master. Alden Gates    male   0.83      0      2              248738   29.0000              NaN        S
79            80         1       3                                                            Dowdell, Miss. Elizabeth  female  30.00      0      0              364516   12.4750              NaN        S
80            81         0       3                                                                Waelens, Mr. Achille    male  22.00      0      0              345767    9.0000              NaN        S
81            82         1       3                                                         Sheerlinck, Mr. Jan Baptist    male  29.00      0      0              345779    9.5000              NaN        S
82            83         1       3                                                      McDermott, Miss. Brigdet Delia  female    NaN      0      0              330932    7.7875              NaN        Q
83            84         0       1                                                             Carrau, Mr. Francisco M    male  28.00      0      0              113059   47.1000              NaN        S
84            85         1       2                                                                 Ilett, Miss. Bertha  female  17.00      0      0          SO/C 14885   10.5000              NaN        S
85            86         1       3                             Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)  female  33.00      3      0             3101278   15.8500              NaN        S
86            87         0       3                                                              Ford, Mr. William Neal    male  16.00      1      3          W./C. 6608   34.3750              NaN        S
87            88         0       3                                                       Slocovski, Mr. Selman Francis    male    NaN      0      0     SOTON/OQ 392086    8.0500              NaN        S
88            89         1       1                                                          Fortune, Miss. Mabel Helen  female  23.00      3      2               19950  263.0000      C23 C25 C27        S
89            90         0       3                                                              Celotti, Mr. Francesco    male  24.00      0      0              343275    8.0500              NaN        S
90            91         0       3                                                                Christmann, Mr. Emil    male  29.00      0      0              343276    8.0500              NaN        S
91            92         0       3                                                          Andreasson, Mr. Paul Edvin    male  20.00      0      0              347466    7.8542              NaN        S
92            93         0       1                                                         Chaffee, Mr. Herbert Fuller    male  46.00      1      0         W.E.P. 5734   61.1750              E31        S
93            94         0       3                                                             Dean, Mr. Bertram Frank    male  26.00      1      2           C.A. 2315   20.5750              NaN        S
94            95         0       3                                                                   Coxon, Mr. Daniel    male  59.00      0      0              364500    7.2500              NaN        S
95            96         0       3                                                         Shorney, Mr. Charles Joseph    male    NaN      0      0              374910    8.0500              NaN        S
96            97         0       1                                                           Goldschmidt, Mr. George B    male  71.00      0      0            PC 17754   34.6542               A5        C

如果想让他们效果一样，需要怎么做？

In [47]:
# read_csv 函数和 read_table 有许多有用的参数，例如 sep 分隔符、header 头部行、index_col 索引列等等。
# 它们的区别只是它们的参数默认值不同，
# 如果我要用 read_table() 可以用下面的设置

ifTableFuncLoadCsv = pd.read_table('Day2 - train.csv', sep=',')
print(ifTableFuncLoadCsv.to_string())

     PassengerId  Survived  Pclass                                                                                Name     Sex    Age  SibSp  Parch              Ticket      Fare            Cabin Embarked
0              1         0       3                                                             Braund, Mr. Owen Harris    male  22.00      1      0           A/5 21171    7.2500              NaN        S
1              2         1       1                                 Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.00      1      0            PC 17599   71.2833              C85        C
2              3         1       3                                                              Heikkinen, Miss. Laina  female  26.00      0      0    STON/O2. 3101282    7.9250              NaN        S
3              4         1       1                                        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.00      1      0              113803   53.1000             C123        S
4              5         0       3                                                            Allen, Mr. William Henry    male  35.00      0      0              373450    8.0500              NaN        S
5              6         0       3                                                                    Moran, Mr. James    male    NaN      0      0              330877    8.4583              NaN        Q
6              7         0       1                                                             McCarthy, Mr. Timothy J    male  54.00      0      0               17463   51.8625              E46        S
7              8         0       3                                                      Palsson, Master. Gosta Leonard    male   2.00      3      1              349909   21.0750              NaN        S
8              9         1       3                                   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.00      0      2              347742   11.1333              NaN        S
9             10         1       2                                                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.00      1      0              237736   30.0708              NaN        C
10            11         1       3                                                     Sandstrom, Miss. Marguerite Rut  female   4.00      1      1             PP 9549   16.7000               G6        S
11            12         1       1                                                            Bonnell, Miss. Elizabeth  female  58.00      0      0              113783   26.5500             C103        S
12            13         0       3                                                      Saundercock, Mr. William Henry    male  20.00      0      0           A/5. 2151    8.0500              NaN        S
13            14         0       3                                                         Andersson, Mr. Anders Johan    male  39.00      1      5              347082   31.2750              NaN        S
14            15         0       3                                                Vestrom, Miss. Hulda Amanda Adolfina  female  14.00      0      0              350406    7.8542              NaN        S
15            16         1       2                                                    Hewlett, Mrs. (Mary D Kingcome)   female  55.00      0      0              248706   16.0000              NaN        S
16            17         0       3                                                                Rice, Master. Eugene    male   2.00      4      1              382652   29.1250              NaN        Q
17            18         1       2                                                        Williams, Mr. Charles Eugene    male    NaN      0      0              244373   13.0000              NaN        S
18            19         0       3                             Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)  female  31.00      1      0              345763   18.0000              NaN        S
19            20         1       3                                                             Masselmani, Mrs. Fatima  female    NaN      0      0                2649    7.2250              NaN        C
20            21         0       2                                                                Fynney, Mr. Joseph J    male  35.00      0      0              239865   26.0000              NaN        S
21            22         1       2                                                               Beesley, Mr. Lawrence    male  34.00      0      0              248698   13.0000              D56        S
22            23         1       3                                                         McGowan, Miss. Anna "Annie"  female  15.00      0      0              330923    8.0292              NaN        Q
23            24         1       1                                                        Sloper, Mr. William Thompson    male  28.00      0      0              113788   35.5000               A6        S
24            25         0       3                                                       Palsson, Miss. Torborg Danira  female   8.00      3      1              349909   21.0750              NaN        S
25            26         1       3                           Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)  female  38.00      1      5              347077   31.3875              NaN        S
26            27         0       3                                                             Emir, Mr. Farred Chehab    male    NaN      0      0                2631    7.2250              NaN        C
27            28         0       1                                                      Fortune, Mr. Charles Alexander    male  19.00      3      2               19950  263.0000      C23 C25 C27        S
28            29         1       3                                                       O'Dwyer, Miss. Ellen "Nellie"  female    NaN      0      0              330959    7.8792              NaN        Q
29            30         0       3                                                                 Todoroff, Mr. Lalio    male    NaN      0      0              349216    7.8958              NaN        S
30            31         0       1                                                            Uruchurtu, Don. Manuel E    male  40.00      0      0            PC 17601   27.7208              NaN        C
31            32         1       1                                      Spencer, Mrs. William Augustus (Marie Eugenie)  female    NaN      1      0            PC 17569  146.5208              B78        C
32            33         1       3                                                            Glynn, Miss. Mary Agatha  female    NaN      0      0              335677    7.7500              NaN        Q
33            34         0       2                                                               Wheadon, Mr. Edward H    male  66.00      0      0          C.A. 24579   10.5000              NaN        S
34            35         0       1                                                             Meyer, Mr. Edgar Joseph    male  28.00      1      0            PC 17604   82.1708              NaN        C
35            36         0       1                                                      Holverson, Mr. Alexander Oskar    male  42.00      1      0              113789   52.0000              NaN        S
36            37         1       3                                                                    Mamee, Mr. Hanna    male    NaN      0      0                2677    7.2292              NaN        C
37            38         0       3                                                            Cann, Mr. Ernest Charles    male  21.00      0      0          A./5. 2152    8.0500              NaN        S
38            39         0       3                                                  Vander Planke, Miss. Augusta Maria  female  18.00      2      0              345764   18.0000              NaN        S
39            40         1       3                                                         Nicola-Yarred, Miss. Jamila  female  14.00      1      0                2651   11.2417              NaN        C
40            41         0       3                                      Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female  40.00      1      0                7546    9.4750              NaN        S
41            42         0       2                            Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)  female  27.00      1      0               11668   21.0000              NaN        S
42            43         0       3                                                                 Kraeff, Mr. Theodor    male    NaN      0      0              349253    7.8958              NaN        C
43            44         1       2                                            Laroche, Miss. Simonne Marie Anne Andree  female   3.00      1      2       SC/Paris 2123   41.5792              NaN        C
44            45         1       3                                                       Devaney, Miss. Margaret Delia  female  19.00      0      0              330958    7.8792              NaN        Q
45            46         0       3                                                            Rogers, Mr. William John    male    NaN      0      0     S.C./A.4. 23567    8.0500              NaN        S
46            47         0       3                                                                   Lennon, Mr. Denis    male    NaN      1      0              370371   15.5000              NaN        Q
47            48         1       3                                                           O'Driscoll, Miss. Bridget  female    NaN      0      0               14311    7.7500              NaN        Q
48            49         0       3                                                                 Samaan, Mr. Youssef    male    NaN      2      0                2662   21.6792              NaN        C
49            50         0       3                                       Arnold-Franchi, Mrs. Josef (Josefine Franchi)  female  18.00      1      0              349237   17.8000              NaN        S
50            51         0       3                                                          Panula, Master. Juha Niilo    male   7.00      4      1             3101295   39.6875              NaN        S
51            52         0       3                                                        Nosworthy, Mr. Richard Cater    male  21.00      0      0          A/4. 39886    7.8000              NaN        S
52            53         1       1                                            Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  49.00      1      0            PC 17572   76.7292              D33        C
53            54         1       2                                  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)  female  29.00      1      0                2926   26.0000              NaN        S
54            55         0       1                                                      Ostby, Mr. Engelhart Cornelius    male  65.00      0      1              113509   61.9792              B30        C
55            56         1       1                                                                   Woolner, Mr. Hugh    male    NaN      0      0               19947   35.5000              C52        S
56            57         1       2                                                                   Rugg, Miss. Emily  female  21.00      0      0          C.A. 31026   10.5000              NaN        S
57            58         0       3                                                                 Novel, Mr. Mansouer    male  28.50      0      0                2697    7.2292              NaN        C
58            59         1       2                                                        West, Miss. Constance Mirium  female   5.00      1      2          C.A. 34651   27.7500              NaN        S
59            60         0       3                                                  Goodwin, Master. William Frederick    male  11.00      5      2             CA 2144   46.9000              NaN        S
60            61         0       3                                                               Sirayanian, Mr. Orsen    male  22.00      0      0                2669    7.2292              NaN        C
61            62         1       1                                                                 Icard, Miss. Amelie  female  38.00      0      0              113572   80.0000              B28      NaN
62            63         0       1                                                         Harris, Mr. Henry Birkhardt    male  45.00      1      0               36973   83.4750              C83        S
63            64         0       3                                                               Skoog, Master. Harald    male   4.00      3      2              347088   27.9000              NaN        S
64            65         0       1                                                               Stewart, Mr. Albert A    male    NaN      0      0            PC 17605   27.7208              NaN        C
65            66         1       3                                                            Moubarek, Master. Gerios    male    NaN      1      1                2661   15.2458              NaN        C
66            67         1       2                                                        Nye, Mrs. (Elizabeth Ramell)  female  29.00      0      0          C.A. 29395   10.5000              F33        S
67            68         0       3                                                            Crease, Mr. Ernest James    male  19.00      0      0           S.P. 3464    8.1583              NaN        S
68            69         1       3                                                     Andersson, Miss. Erna Alexandra  female  17.00      4      2             3101281    7.9250              NaN        S
69            70         0       3                                                                   Kink, Mr. Vincenz    male  26.00      2      0              315151    8.6625              NaN        S
70            71         0       2                                                          Jenkin, Mr. Stephen Curnow    male  32.00      0      0          C.A. 33111   10.5000              NaN        S
71            72         0       3                                                          Goodwin, Miss. Lillian Amy  female  16.00      5      2             CA 2144   46.9000              NaN        S
72            73         0       2                                                                Hood, Mr. Ambrose Jr    male  21.00      0      0        S.O.C. 14879   73.5000              NaN        S
73            74         0       3                                                         Chronopoulos, Mr. Apostolos    male  26.00      1      0                2680   14.4542              NaN        C
74            75         1       3                                                                       Bing, Mr. Lee    male  32.00      0      0                1601   56.4958              NaN        S
75            76         0       3                                                             Moen, Mr. Sigurd Hansen    male  25.00      0      0              348123    7.6500            F G73        S
76            77         0       3                                                                   Staneff, Mr. Ivan    male    NaN      0      0              349208    7.8958              NaN        S
77            78         0       3                                                            Moutal, Mr. Rahamin Haim    male    NaN      0      0              374746    8.0500              NaN        S
78            79         1       2                                                       Caldwell, Master. Alden Gates    male   0.83      0      2              248738   29.0000              NaN        S
79            80         1       3                                                            Dowdell, Miss. Elizabeth  female  30.00      0      0              364516   12.4750              NaN        S
80            81         0       3                                                                Waelens, Mr. Achille    male  22.00      0      0              345767    9.0000              NaN        S
81            82         1       3                                                         Sheerlinck, Mr. Jan Baptist    male  29.00      0      0              345779    9.5000              NaN        S
82            83         1       3                                                      McDermott, Miss. Brigdet Delia  female    NaN      0      0              330932    7.7875              NaN        Q
83            84         0       1                                                             Carrau, Mr. Francisco M    male  28.00      0      0              113059   47.1000              NaN        S
84            85         1       2                                                                 Ilett, Miss. Bertha  female  17.00      0      0          SO/C 14885   10.5000              NaN        S
85            86         1       3                             Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)  female  33.00      3      0             3101278   15.8500              NaN        S
86            87         0       3                                                              Ford, Mr. William Neal    male  16.00      1      3          W./C. 6608   34.3750              NaN        S
87            88         0       3                                                       Slocovski, Mr. Selman Francis    male    NaN      0      0     SOTON/OQ 392086    8.0500              NaN        S
88            89         1       1                                                          Fortune, Miss. Mabel Helen  female  23.00      3      2               19950  263.0000      C23 C25 C27        S
89            90         0       3                                                              Celotti, Mr. Francesco    male  24.00      0      0              343275    8.0500              NaN        S
90            91         0       3                                                                Christmann, Mr. Emil    male  29.00      0      0              343276    8.0500              NaN        S
91            92         0       3                                                          Andreasson, Mr. Paul Edvin    male  20.00      0      0              347466    7.8542              NaN        S
92            93         0       1                                                         Chaffee, Mr. Herbert Fuller    male  46.00      1      0         W.E.P. 5734   61.1750              E31        S
93            94         0       3                                                             Dean, Mr. Bertram Frank    male  26.00      1      2           C.A. 2315   20.5750              NaN        S
94            95         0       3                                                                   Coxon, Mr. Daniel    male  59.00      0      0              364500    7.2500              NaN        S
95            96         0       3                                                         Shorney, Mr. Charles Joseph    male    NaN      0      0              374910    8.0500              NaN        S
96            97         0       1                                                           Goldschmidt, Mr. George B    male  71.00      0      0            PC 17754   34.6542               A5        C

【总结】加载的数据是所有工作的第一步，我们的工作会接触到不同的数据格式（eg:.csv;.tsv;.xlsx）,但是加载的方法和思路都是一样的，在以后工作和做项目的过程中，遇到之前没有碰到的问题，要多多查资料吗，使用google，了解业务逻辑，明白输入和输出是什么。

#### 1.1.3 任务三：每1000行为一个数据模块，逐块读取

In [48]:
chunker = pd.read_csv('Day2 - train.csv' , chunksize = 1000)

for i in chunker:
    print(i)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

【思考】什么是逐块读取？为什么要逐块读取呢？

【提示】大家可以chunker(数据块)是什么类型？用`for`循环打印出来出处具体的样子是什么？

In [49]:
# 逐块读取就是将文本分成若干块；
# 对于几百MB的CSV文件，可以直接使用pd.read_csv（）进行读取。
# 然而如果csv文件太大，达到几个Gb，这种方法就不可取。这时应使用chunk，进行分块读取。

chunker = chunker = pd.read_csv('Day2 - train.csv' , chunksize = 100) # 改小以更明显
print(type(chunker))

print('\n')

for i in chunker:
    print(i)

<class 'pandas.io.parsers.readers.TextFileReader'>


    PassengerId  Survived  Pclass  \
0             1         0       3
1             2         1       1
2             3         1       3
3             4         1       1
4             5         0       3
..          ...       ...     ...
95           96         0       3
96           97         0       1
97           98         1       1
98           99         1       2
99          100         0       2

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                              Heikkinen, Miss. Laina  female  26.0      0
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                            Allen, Mr. William Henry    male  35.0      0
..                                                ...     ...   ...    ...
95                        Shorney, Mr. Charles Joseph    male   NaN      0
96                          Goldschmidt, Mr. George B    male  71.0      0
97                    Greenfield, Mr. William Bertram    male  23.0      0
98               Doling, Mrs. John T (Ada Julia Bone)  female  34.0      0
99                                  Kantor, Mr. Sinai    male  34.0      1

    Parch            Ticket     Fare    Cabin Embarked
0       0         A/5 21171   7.2500      NaN        S
1       0          PC 17599  71.2833      C85        C
2       0  STON/O2. 3101282   7.9250      NaN        S
3       0            113803  53.1000     C123        S
4       0            373450   8.0500      NaN        S
..    ...               ...      ...      ...      ...
95      0            374910   8.0500      NaN        S
96      0          PC 17754  34.6542       A5        C
97      1          PC 17759  63.3583  D10 D12        C
98      1            231919  23.0000      NaN        S
99      0            244367  26.0000      NaN        S

[100 rows x 12 columns]
     PassengerId  Survived  Pclass                                    Name  \
100          101         0       3                 Petranec, Miss. Matilda
101          102         0       3        Petroff, Mr. Pastcho ("Pentcho")
102          103         0       1               White, Mr. Richard Frasar
103          104         0       3              Johansson, Mr. Gustaf Joel
104          105         0       3          Gustafsson, Mr. Anders Vilhelm
..           ...       ...     ...                                     ...
195          196         1       1                    Lurette, Miss. Elise
196          197         0       3                     Mernagh, Mr. Robert
197          198         0       3        Olsen, Mr. Karl Siegwart Andreas
198          199         1       3        Madigan, Miss. Margaret "Maggie"
199          200         0       2  Yrois, Miss. Henriette ("Mrs Harbeck")

        Sex   Age  SibSp  Parch    Ticket      Fare Cabin Embarked
100  female  28.0      0      0    349245    7.8958   NaN        S
101    male   NaN      0      0    349215    7.8958   NaN        S
102    male  21.0      0      1     35281   77.2875   D26        S
103    male  33.0      0      0      7540    8.6542   NaN        S
104    male  37.0      2      0   3101276    7.9250   NaN        S
..      ...   ...    ...    ...       ...       ...   ...      ...
195  female  58.0      0      0  PC 17569  146.5208   B80        C
196    male   NaN      0      0    368703    7.7500   NaN        Q
197    male  42.0      0      1      4579    8.4042   NaN        S
198  female   NaN      0      0    370370    7.7500   NaN        Q
199  female  24.0      0      0    248747   13.0000   NaN        S

[100 rows x 12 columns]
     PassengerId  Survived  Pclass  \
200          201         0       3
201          202         0       3
202          203         0       3
203          204         0       3
204          205         1       3
..           ...       ...     ...
295          296         0       1
296          297         0       3
297          298         0       1
298          299         1       1
299          300         1       1

                                                Name     Sex   Age  SibSp  \
200                   Vande Walle, Mr. Nestor Cyriel    male  28.0      0
201                              Sage, Mr. Frederick    male   NaN      8
202                       Johanson, Mr. Jakob Alfred    male  34.0      0
203                             Youseff, Mr. Gerious    male  45.5      0
204                         Cohen, Mr. Gurshon "Gus"    male  18.0      0
..                                               ...     ...   ...    ...
295                                Lewy, Mr. Ervin G    male   NaN      0
296                               Hanna, Mr. Mansour    male  23.5      0
297                     Allison, Miss. Helen Loraine  female   2.0      1
298                            Saalfeld, Mr. Adolphe    male   NaN      0
299  Baxter, Mrs. James (Helene DeLaudeniere Chaput)  female  50.0      0

     Parch    Ticket      Fare    Cabin Embarked
200      0    345770    9.5000      NaN        S
201      2  CA. 2343   69.5500      NaN        S
202      0   3101264    6.4958      NaN        S
203      0      2628    7.2250      NaN        C
204      0  A/5 3540    8.0500      NaN        S
..     ...       ...       ...      ...      ...
295      0  PC 17612   27.7208      NaN        C
296      0      2693    7.2292      NaN        C
297      2    113781  151.5500  C22 C26        S
298      0     19988   30.5000     C106        S
299      1  PC 17558  247.5208  B58 B60        C

[100 rows x 12 columns]
     PassengerId  Survived  Pclass                                      Name  \
300          301         1       3  Kelly, Miss. Anna Katherine "Annie Kate"
301          302         1       3                        McCoy, Mr. Bernard
302          303         0       3           Johnson, Mr. William Cahoone Jr
303          304         1       2                       Keane, Miss. Nora A
304          305         0       3         Williams, Mr. Howard Hugh "Harry"
..           ...       ...     ...                                       ...
395          396         0       3                       Johansson, Mr. Erik
396          397         0       3                       Olsson, Miss. Elina
397          398         0       2                   McKane, Mr. Peter David
398          399         0       2                          Pain, Dr. Alfred
399          400         1       2          Trout, Mrs. William H (Jessie L)

        Sex   Age  SibSp  Parch    Ticket     Fare Cabin Embarked
300  female   NaN      0      0      9234   7.7500   NaN        Q
301    male   NaN      2      0    367226  23.2500   NaN        Q
302    male  19.0      0      0      LINE   0.0000   NaN        S
303  female   NaN      0      0    226593  12.3500  E101        Q
304    male   NaN      0      0  A/5 2466   8.0500   NaN        S
..      ...   ...    ...    ...       ...      ...   ...      ...
395    male  22.0      0      0    350052   7.7958   NaN        S
396  female  31.0      0      0    350407   7.8542   NaN        S
397    male  46.0      0      0     28403  26.0000   NaN        S
398    male  23.0      0      0    244278  10.5000   NaN        S
399  female  28.0      0      0    240929  12.6500   NaN        S

[100 rows x 12 columns]
     PassengerId  Survived  Pclass  \
400          401         1       3
401          402         0       3
402          403         0       3
403          404         0       3
404          405         0       3
..           ...       ...     ...
495          496         0       3
496          497         1       1
497          498         0       3
498          499         0       1
499          500         0       3

                                                Name     Sex   Age  SibSp  \
400                               Niskanen, Mr. Juha    male  39.0      0
401                                  Adams, Mr. John    male  26.0      0
402                         Jussila, Miss. Mari Aina  female  21.0      1
403                   Hakkarainen, Mr. Pekka Pietari    male  28.0      1
404                          Oreskovic, Miss. Marija  female  20.0      0
..                                               ...     ...   ...    ...
495                            Yousseff, Mr. Gerious    male   NaN      0
496                   Eustis, Miss. Elizabeth Mussey  female  54.0      1
497                  Shellard, Mr. Frederick William    male   NaN      0
498  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0      1
499                               Svensson, Mr. Olof    male  24.0      0

     Parch             Ticket      Fare    Cabin Embarked
400      0  STON/O 2. 3101289    7.9250      NaN        S
401      0             341826    8.0500      NaN        S
402      0               4137    9.8250      NaN        S
403      0   STON/O2. 3101279   15.8500      NaN        S
404      0             315096    8.6625      NaN        S
..     ...                ...       ...      ...      ...
495      0               2627   14.4583      NaN        C
496      0              36947   78.2667      D20        C
497      0          C.A. 6212   15.1000      NaN        S
498      2             113781  151.5500  C22 C26        S
499      0             350035    7.7958      NaN        S

[100 rows x 12 columns]
     PassengerId  Survived  Pclass  \
500          501         0       3
501          502         0       3
502          503         0       3
503          504         0       3
504          505         1       1
..           ...       ...     ...
595          596         0       3
596          597         1       2
597          598         0       3
598          599         0       3
599          600         1       1

                                             Name     Sex   Age  SibSp  Parch  \
500                              Calic, Mr. Petar    male  17.0      0      0
501                           Canavan, Miss. Mary  female  21.0      0      0
502                O'Sullivan, Miss. Bridget Mary  female   NaN      0      0
503                Laitinen, Miss. Kristina Sofia  female  37.0      0      0
504                         Maioni, Miss. Roberta  female  16.0      0      0
..                                            ...     ...   ...    ...    ...
595                   Van Impe, Mr. Jean Baptiste    male  36.0      1      1
596                    Leitch, Miss. Jessie Wills  female   NaN      0      0
597                           Johnson, Mr. Alfred    male  49.0      0      0
598                             Boulos, Mr. Hanna    male   NaN      0      0
599  Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")    male  49.0      1      0

       Ticket     Fare Cabin Embarked
500    315086   8.6625   NaN        S
501    364846   7.7500   NaN        Q
502    330909   7.6292   NaN        Q
503      4135   9.5875   NaN        S
504    110152  86.5000   B79        S
..        ...      ...   ...      ...
595    345773  24.1500   NaN        S
596    248727  33.0000   NaN        S
597      LINE   0.0000   NaN        S
598      2664   7.2250   NaN        C
599  PC 17485  56.9292   A20        C

[100 rows x 12 columns]
     PassengerId  Survived  Pclass  \
600          601         1       2
601          602         0       3
602          603         0       1
603          604         0       3
604          605         1       1
..           ...       ...     ...
695          696         0       2
696          697         0       3
697          698         1       3
698          699         0       1
699          700         0       3

                                                  Name     Sex   Age  SibSp  \
600  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  female  24.0      2
601                               Slabenoff, Mr. Petco    male   NaN      0
602                          Harrington, Mr. Charles H    male   NaN      0
603                          Torber, Mr. Ernst William    male  44.0      0
604                    Homer, Mr. Harry ("Mr E Haven")    male  35.0      0
..                                                 ...     ...   ...    ...
695                         Chapman, Mr. Charles Henry    male  52.0      0
696                                   Kelly, Mr. James    male  44.0      0
697                   Mullens, Miss. Katherine "Katie"  female   NaN      0
698                           Thayer, Mr. John Borland    male  49.0      1
699           Humblen, Mr. Adolf Mathias Nicolai Olsen    male  42.0      0

     Parch  Ticket      Fare  Cabin Embarked
600      1  243847   27.0000    NaN        S
601      0  349214    7.8958    NaN        S
602      0  113796   42.4000    NaN        S
603      0  364511    8.0500    NaN        S
604      0  111426   26.5500    NaN        C
..     ...     ...       ...    ...      ...
695      0  248731   13.5000    NaN        S
696      0  363592    8.0500    NaN        S
697      0   35852    7.7333    NaN        Q
698      1   17421  110.8833    C68        C
699      0  348121    7.6500  F G63        S

[100 rows x 12 columns]
     PassengerId  Survived  Pclass  \
700          701         1       1
701          702         1       1
702          703         0       3
703          704         0       3
704          705         0       3
..           ...       ...     ...
795          796         0       2
796          797         1       1
797          798         1       3
798          799         0       3
799          800         0       3

                                                  Name     Sex   Age  SibSp  \
700  Astor, Mrs. John Jacob (Madeleine Talmadge Force)  female  18.0      1
701                   Silverthorne, Mr. Spencer Victor    male  35.0      0
702                              Barbara, Miss. Saiide  female  18.0      0
703                              Gallagher, Mr. Martin    male  25.0      0
704                            Hansen, Mr. Henrik Juul    male  26.0      1
..                                                 ...     ...   ...    ...
795                                 Otter, Mr. Richard    male  39.0      0
796                        Leader, Dr. Alice (Farnham)  female  49.0      0
797                                   Osman, Mrs. Mara  female  31.0      0
798                       Ibrahim Shawah, Mr. Yousseff    male  30.0      0
799  Van Impe, Mrs. Jean Baptiste (Rosalie Paula Go...  female  30.0      1

     Parch    Ticket      Fare    Cabin Embarked
700      0  PC 17757  227.5250  C62 C64        C
701      0  PC 17475   26.2875      E24        S
702      1      2691   14.4542      NaN        C
703      0     36864    7.7417      NaN        Q
704      0    350025    7.8542      NaN        S
..     ...       ...       ...      ...      ...
795      0     28213   13.0000      NaN        S
796      0     17465   25.9292      D17        S
797      0    349244    8.6833      NaN        S
798      0      2685    7.2292      NaN        C
799      1    345773   24.1500      NaN        S

[100 rows x 12 columns]
     PassengerId  Survived  Pclass  \
800          801         0       2
801          802         1       2
802          803         1       1
803          804         1       3
804          805         1       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                            Name     Sex    Age  SibSp  Parch  \
800                         Ponesell, Mr. Martin    male  34.00      0      0
801  Collyer, Mrs. Harvey (Charlotte Annie Tate)  female  31.00      1      1
802          Carter, Master. William Thornton II    male  11.00      1      2
803              Thomas, Master. Assad Alexander    male   0.42      0      1
804                      Hedman, Mr. Oskar Arvid    male  27.00      0      0
..                                           ...     ...    ...    ...    ...
886                        Montvila, Rev. Juozas    male  27.00      0      0
887                 Graham, Miss. Margaret Edith  female  19.00      0      0
888     Johnston, Miss. Catherine Helen "Carrie"  female    NaN      1      2
889                        Behr, Mr. Karl Howell    male  26.00      0      0
890                          Dooley, Mr. Patrick    male  32.00      0      0

         Ticket      Fare    Cabin Embarked
800      250647   13.0000      NaN        S
801  C.A. 31921   26.2500      NaN        S
802      113760  120.0000  B96 B98        S
803        2625    8.5167      NaN        C
804      347089    6.9750      NaN        S
..          ...       ...      ...      ...
886      211536   13.0000      NaN        S
887      112053   30.0000      B42        S
888  W./C. 6607   23.4500      NaN        S
889      111369   30.0000     C148        C
890      370376    7.7500      NaN        Q

[91 rows x 12 columns]

#### 1.1.4 任务四：将表头改成中文，索引改为乘客ID [对于某些英文资料，我们可以通过翻译来更直观的熟悉我们的数据]
PassengerId => 乘客ID   
Survived    => 是否幸存   
Pclass      => 乘客等级(1/2/3等舱位)  
Name        => 乘客姓名  
Sex         => 性别                 
Age         => 年龄                 
SibSp       => 堂兄弟/妹个数  
Parch       => 父母与小孩个数  
Ticket      => 船票信息             
Fare        => 票价                
Cabin       => 客舱                
Embarked    => 登船港口

In [50]:
df = pd.read_csv(absPath , names = ['乘客ID' , '是否幸存' , '乘客等级(1/2/3等舱位)' , '乘客姓名' , '性别' , '年龄' , '堂兄弟/妹个数' , '父母与小孩个数' , '船票信息' , '票价' , '客舱' , '登船港口'] , index_col = '乘客ID' , header = 0)
df.head()

,是否幸存,乘客等级(1/2/3等舱位),乘客姓名,性别,年龄,堂兄弟/妹个数,父母与小孩个数,船票信息,票价,客舱,登船港口
乘客ID,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

【思考】所谓将表头改为中文其中一个思路是：将英文列名表头替换成中文。还有其他的方法吗？

In [51]:
# rename() - 任意的行名(index)和列名(columns)的修改

df_new_1 = df.reset_index()
df_new_1 = df_new_1.rename(columns={'乘客ID': '帕塞至二艾迪'})
print(df_new_1)

# add_prefix(), add_suffix() - 列名的接头词和结尾词的追加

df_new_2 = df_new_1.add_prefix('事故数据-')
print(df_new_2)

# 行名和列名全部修改

df_new_3 = pd.read_csv(absPath)
df_new_3.columns = ['乘客ID' , '是否幸存' , '乘客等级(1/2/3等舱位)' , '乘客姓名' , '性别' , '年龄' , '堂兄弟/妹个数' , '父母与小孩个数' , '船票信息' , '票价' , '客舱' , '登船港口'] 
print(df_new_3)

     帕塞至二艾迪  是否幸存  乘客等级(1/2/3等舱位)  \
0         1     0               3
1         2     1               1
2         3     1               3
3         4     1               1
4         5     0               3
..      ...   ...             ...
886     887     0               2
887     888     1               1
888     889     0               3
889     890     1               1
890     891     0               3

                                                  乘客姓名      性别    年龄  堂兄弟/妹个数  \
0                              Braund, Mr. Owen Harris    male  22.0        1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0        1
2                               Heikkinen, Miss. Laina  female  26.0        0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0        1
4                             Allen, Mr. William Henry    male  35.0        0
..                                                 ...     ...   ...      ...
886                              Montvila, Rev. Juozas    male  27.0        0
887                       Graham, Miss. Margaret Edith  female  19.0        0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN        1
889                              Behr, Mr. Karl Howell    male  26.0        0
890                                Dooley, Mr. Patrick    male  32.0        0

     父母与小孩个数              船票信息       票价    客舱 登船港口
0          0         A/5 21171   7.2500   NaN    S
1          0          PC 17599  71.2833   C85    C
2          0  STON/O2. 3101282   7.9250   NaN    S
3          0            113803  53.1000  C123    S
4          0            373450   8.0500   NaN    S
..       ...               ...      ...   ...  ...
886        0            211536  13.0000   NaN    S
887        0            112053  30.0000   B42    S
888        2        W./C. 6607  23.4500   NaN    S
889        0            111369  30.0000  C148    C
890        0            370376   7.7500   NaN    Q

[891 rows x 12 columns]
     事故数据-帕塞至二艾迪  事故数据-是否幸存  事故数据-乘客等级(1/2/3等舱位)  \
0              1          0                    3
1              2          1                    1
2              3          1                    3
3              4          1                    1
4              5          0                    3
..           ...        ...                  ...
886          887          0                    2
887          888          1                    1
888          889          0                    3
889          890          1                    1
890          891          0                    3

                                             事故数据-乘客姓名 事故数据-性别  事故数据-年龄  \
0                              Braund, Mr. Owen Harris    male     22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female     38.0
2                               Heikkinen, Miss. Laina  female     26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female     35.0
4                             Allen, Mr. William Henry    male     35.0
..                                                 ...     ...      ...
886                              Montvila, Rev. Juozas    male     27.0
887                       Graham, Miss. Margaret Edith  female     19.0
888           Johnston, Miss. Catherine Helen "Carrie"  female      NaN
889                              Behr, Mr. Karl Howell    male     26.0
890                                Dooley, Mr. Patrick    male     32.0

     事故数据-堂兄弟/妹个数  事故数据-父母与小孩个数         事故数据-船票信息  事故数据-票价 事故数据-客舱 事故数据-登船港口
0               1             0         A/5 21171   7.2500     NaN         S
1               1             0          PC 17599  71.2833     C85         C
2               0             0  STON/O2. 3101282   7.9250     NaN         S
3               1             0            113803  53.1000    C123         S
4               0             0            373450   8.0500     NaN         S
..            ...           ...               ...      ...     ...       ...
886             0             0            211536  13.0000     NaN         S
887             0             0            112053  30.0000     B42         S
888             1             2        W./C. 6607  23.4500     NaN         S
889             0             0            111369  30.0000    C148         C
890             0             0            370376   7.7500     NaN         Q

[891 rows x 12 columns]
     乘客ID  是否幸存  乘客等级(1/2/3等舱位)  \
0       1     0               3
1       2     1               1
2       3     1               3
3       4     1               1
4       5     0               3
..    ...   ...             ...
886   887     0               2
887   888     1               1
888   889     0               3
889   890     1               1
890   891     0               3

                                                  乘客姓名      性别    年龄  堂兄弟/妹个数  \
0                              Braund, Mr. Owen Harris    male  22.0        1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0        1
2                               Heikkinen, Miss. Laina  female  26.0        0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0        1
4                             Allen, Mr. William Henry    male  35.0        0
..                                                 ...     ...   ...      ...
886                              Montvila, Rev. Juozas    male  27.0        0
887                       Graham, Miss. Margaret Edith  female  19.0        0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN        1
889                              Behr, Mr. Karl Howell    male  26.0        0
890                                Dooley, Mr. Patrick    male  32.0        0

     父母与小孩个数              船票信息       票价    客舱 登船港口
0          0         A/5 21171   7.2500   NaN    S
1          0          PC 17599  71.2833   C85    C
2          0  STON/O2. 3101282   7.9250   NaN    S
3          0            113803  53.1000  C123    S
4          0            373450   8.0500   NaN    S
..       ...               ...      ...   ...  ...
886        0            211536  13.0000   NaN    S
887        0            112053  30.0000   B42    S
888        2        W./C. 6607  23.4500   NaN    S
889        0            111369  30.0000  C148    C
890        0            370376   7.7500   NaN    Q

[891 rows x 12 columns]

### 1.2 初步观察
导入数据后，你可能要对数据的整体结构和样例进行概览，比如说，数据大小、有多少列，各列都是什么格式的，是否包含null等

#### 1.2.1 任务一：查看数据的基本信息

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   是否幸存            891 non-null    int64
 1   乘客等级(1/2/3等舱位)  891 non-null    int64
 2   乘客姓名            891 non-null    object
 3   性别              891 non-null    object
 4   年龄              714 non-null    float64
 5   堂兄弟/妹个数         891 non-null    int64
 6   父母与小孩个数         891 non-null    int64
 7   船票信息            891 non-null    object
 8   票价              891 non-null    float64
 9   客舱              204 non-null    object
 10  登船港口            889 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 83.5+ KB

#### 1.2.2 任务二：观察表格前10行的数据和后15行的数据

In [53]:
df.head(10)

,是否幸存,乘客等级(1/2/3等舱位),乘客姓名,性别,年龄,堂兄弟/妹个数,父母与小孩个数,船票信息,票价,客舱,登船港口
乘客ID,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [54]:
df.tail(15)

,是否幸存,乘客等级(1/2/3等舱位),乘客姓名,性别,年龄,堂兄弟/妹个数,父母与小孩个数,船票信息,票价,客舱,登船港口
乘客ID,,,,,,,,,,,
877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

#### 1.2.4 任务三：判断数据是否为空，为空的地方返回True，其余地方返回False

In [55]:
df.isnull().head()

,是否幸存,乘客等级(1/2/3等舱位),乘客姓名,性别,年龄,堂兄弟/妹个数,父母与小孩个数,船票信息,票价,客舱,登船港口
乘客ID,,,,,,,,,,,
1,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,True,False

【总结】上面的操作都是数据分析中对于数据本身的观察

在分析数据时，可以从多个方面观察和理解数据，以便更全面地了解其特征和潜在的模式。以下是一些常见的观察和分析方面：

1. **统计描述**：
   - **描述性统计**：均值、中位数、方差、标准差、最小值、最大值、四分位数等。
   - **分布**：查看数据的分布情况（如正态分布、偏态分布等）。

2. **数据可视化**：
   - **直方图**：显示数据分布的频率。
   - **箱线图**：显示数据的分布特征及异常值。
   - **散点图**：观察两个变量之间的关系。
   - **折线图**：查看数据随时间的变化趋势。
   - **条形图/柱状图**：比较不同类别的数据。
   - **热图**：显示矩阵数据的热度（如相关性矩阵）。

3. **数据关系**：
   - **相关性分析**：查看不同变量之间的相关性，常用的度量有皮尔逊相关系数和斯皮尔曼相关系数。
   - **协方差矩阵**：显示变量之间的协方差。

4. **数据分组**：
   - **分组统计**：按某个或多个变量分组，计算组内的统计量（如均值、中位数）。
   - **透视表**：创建数据的多维汇总表。

5. **时间序列分析**：
   - **趋势**：观察数据随时间的变化趋势。
   - **季节性**：查看数据是否有季节性波动。
   - **周期性**：分析数据的周期性变化。

6. **异常检测**：
   - **离群点分析**：识别和分析数据中的异常值。
   - **异常检测算法**：使用机器学习算法检测异常（如孤立森林、DBSCAN）。

7. **数据分布**：
   - **概率密度函数 (PDF)** 和 **累积分布函数 (CDF)**：查看数据的概率分布。
   - **核密度估计 (KDE)**：平滑数据分布的估计。

8. **分类和聚类**：
   - **分类分析**：查看数据属于哪个类别（如使用决策树、随机森林等分类算法）。
   - **聚类分析**：将数据分成不同的组（如K-means聚类、层次聚类）。

9. **特征工程**：
   - **特征提取**：从数据中提取有用的特征。
   - **特征选择**：选择对模型最有用的特征。

10. **假设检验**：
    - **t检验**：比较两组数据的均值是否有显著差异。
    - **卡方检验**：检验分类变量的独立性。
    - **ANOVA**：分析多组数据的均值差异。

通过从这些不同方面观察和分析数据，可以获得更全面的理解，并且可以为进一步的数据建模和决策提供有力支持。

【思考】对于一个数据，还可以从哪些方面来观察？找找答案，这个将对下面的数据分析有很大的帮助

### 1.3 保存数据

#### 1.3.1 任务一：将你加载并做出改变的数据，在工作目录下保存为一个新文件train_chinese.csv

In [56]:
# 注意：不同的操作系统保存下来可能会有乱码。大家可以加入`encoding='GBK' 或者 ’encoding = ’utf-8‘‘`
df.to_csv('Day2 - train_chinese.csv',encoding='utf-8')

【总结】数据的加载以及入门，接下来就要接触数据本身的运算，我们将主要掌握numpy和pandas在工作和项目场景的运用。